import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My First NextJS App',
  description: 'Generated by Irfan',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>HEADER FROM LAYOUTJS</h1>
        {children}</body>
    </html>
  )
}
